### ISSUE TITLE
Blurring Only Certain Notes

### ISSUE THREAD

**Issue by santiyounger** [jillalberts/privacy-glasses#1]
Thanks for making this. I have a use case that I think would be extremely useful.

I make videos on Obsidian on YouTube https://www.youtube.com/c/SantiYounger/videos

since I record my screen and show a lot of my Obsidian notes, it's always a challenge to filter out what is private.

What I'd love to be able to do, is to only blur certain notes.

That way  I can freely show notes that I'm okay with sharing, but if I ever stumble upon a private note the plugin could blur that specific note.

Ideally this could be done by setting a tag like `#private` onto a note, and once the plugin it's turned on, now every note with that tag is blurred out.

Ideally the title name would also be blurred out, if possible in the file explorer as well.

These are some of my initial ideas on how this feature could work.

I definitely took some inspiration from a Roam research plugin feature called "Privacy Mode" which I think can serve as inspiration for what this plugin could do.
https://www.youtube.com/watch?v=f1UR9dMR_k0

## Beyond my use case

Of course not everyone records their screens when they use Obsidian. However I still see a lot of people benefit from this

### example 1

sharing screenshots in the forum when asking for help or reporting bugs, it'd be extremely useful for people to easily filter sections of their notes.

### example 2

For being in public while using Obsidian and wishing to blur things out, it'd be useful to only blur out specific things, instead of having to write while the text is blurry.

Thanks for considering this, great work with this plugin so far, really appreciate it!

**Comment by yo-goto** [comment]
It's a nice idea. 
I'm currently planing localized obsidian talks with Japanese users. If this feature is implemented, many users will not hesitate to share their vault and knowledge. 

Please consider adding this feature!

**Comment by santiyounger** [comment]
> It's a nice idea.
> I'm currently planing localized obsidian talks with Japanese users. If this feature is implemented, many users will not hesitate to share their vault and knowledge.
> 
> Please consider adding this feature!

For sure, it would make this plugin 10x better!

**Comment by santiyounger** [comment]
Thanks for the update @jillalberts hope someone can take on this project, it's a very useful one. In my case I make videos on Obsidian, and being able to implement this feature would be awesome

Good luck with your future projects @jillalberts, thanks for starting this cool plugin. Hope someone can carry on this project

Thanks!

**Comment by jillalberts** [comment]
Version 0.7.0 now has the ability to blur notes in certain specified folders, thanks to the work of @0xorial .

**Comment by jillalberts** [comment]
In addition to the ability to blur notes in specific folders, Version 0.7.1 now has the new feature to designate a "private note marker" that will make sure a note gets blurred if it contains that text. Again thanks to the work of @0xorial
