### ISSUE TITLE
[Feature Request] Option to blur only the content underneath a header

### ISSUE THREAD

**Issue by Trikzon** [jillalberts/privacy-glasses#19]
For example, if you have a note such as:

2023-07-03.md
```md
## Journal
Some secret stuff

## Notes
Stuff that isn't so sensitive

```

I'd like to blur everything under the Journal header automatically, but not blur the rest of the note

**Comment by connradolisboa** [comment]
I would really like this feature too.

**Comment by aurepereira** [comment]
@jillalberts @Trikzon @connradolisboa spent a bit of time working on this issue today. A PR is almost ready, though I am still having second thoughts about which icon to use in the sidebar.

Currently, here's the icon I am using: https://icon-sets.iconify.design/ph/eyeglasses/ Care to chime in? What do you think? 🙃
