### ISSUE TITLE
Show the text where the cursor is

### ISSUE THREAD

**Issue by zhxrrb** [jillalberts/privacy-glasses#2]

**Comment by zhxrrb** [comment]
This plugin is really a lifesaver for social phobics! Thank you so much for developing this plugin.
But I encountered a little problem when using it. When I use this plugin in edit mode, all the text is not visible, which affects typing. And text only shows when I put the mouse to certain place. I hope to be able to display the current text according to the position of the cursor, instead of blurring all the text.
Thanks for your work!

**Comment by nyzhb000919** [comment]
I'm also looking forward the same feature

**Comment by nyzhb000919** [comment]
I just find another solution: use “Stille” plug-in and set the "Opacity level for unfocused text" to 0.

**Comment by zhxrrb** [comment]
Great! This plugin "stille" works for me well ! I set the value to be 0.1 which suits me better. Thanks a lot.

**Comment by jillalberts** [comment]
Hello, 
I am no longer working on this project and am unlikely to return to it; it is pretty much abandoned. But the code is open-source and distributed under the MIT license, so anyone who wants to fix or improve anything is free to fork the project and do pretty much whatever they'd like.

**Comment by jillalberts** [comment]
Version 0.7.1, just released, has the "Reveal Under Caret" feature thanks to the work of @0xorial
