### ISSUE TITLE
[Feature Request] Setting for disabling "hover to reveal"

### ISSUE THREAD

**Issue by Paradox86** [jillalberts/privacy-glasses#4]
Can you perhaps add a setting to disable "hover to reveal"?

**Comment by jillalberts** [comment]
Hello, 
I am no longer working on this project and am unlikely to return to it; it is pretty much abandoned. But the code is open-source and distributed under the MIT license, so anyone who wants to fix or improve anything is free to fork the project and do pretty much whatever they'd like.

**Comment by jillalberts** [comment]
This feature is now available in Version 0.7.0 thanks to the work of @0xorial .
