### ISSUE TITLE
Breaks in insider build WYSIWYG 

### ISSUE THREAD

**Issue by EtherealIntellect** [jillalberts/privacy-glasses#5]
Not sure if it's too soon to mention, but i find that in the insider build it only blurs the sides/menus and not the new WYSIWYG mode. It's still evolving , so it might change (my font custom css broke too), but I thought I'd just start some activity here just in case

**Comment by Benature** [comment]
same issue (mine is not insider)

**Comment by Trikzon** [comment]
Same here. Specifically, the plugin doesn't work in the released Live Preview mode.

**Comment by leoccyao** [comment]
Same issue (and is also an issue with mobile). Probably due to a difference in CodeMirror versions. For now I'm still using the legacy editor, but hoping that someone with CM6 experience can figure this out.

**Comment by jillalberts** [comment]
Hello, 
I am no longer working on this project and am unlikely to return to it; it is pretty much abandoned. But the code is open-source and distributed under the MIT license, so anyone who wants to fix or improve anything is free to fork the project and do pretty much whatever they'd like.
