### ISSUE TITLE
Why does this plugin fail to load?

### ISSUE THREAD

**Issue by bitons** [jillalberts/privacy-glasses#9]
I download this plugin in community plugins  but it can not be loaded. I don't know how to deal with it.

>Failed to load plugin privacy-glasses

**Comment by jillalberts** [comment]
It's because I messed up the release of 0.5.1! Sorry about that. I just pushed 0.5.2, so try checking for plugin updates, installing the update, and then re-activating the plugin. It should work better for you now.

Thanks for letting me know about the issue.
